title: "Personal Blog"
email: 
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    coderay:
      css: class # 'class' or 'style'
      line_numbers: true
  syntax_highlighter:
    enable: true
    default_lang: ruby
    span:
      class: 'highlight'
    block:
      class: 'codehilite'
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Daniel
    display_name: Daniel
    avatar: 'assets/images/mesmall.png'
    email: xxxxxxx@gmail.com
    web:  
    twitter:  
    description: "A human."
# Social
social:
  instagram:  
  
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives