title: "danyelmorales.github.io"
email: 
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Daniel
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    coderay:
      css: class # 'class' or 'style'
      line_numbers: true
  syntax_highlighter:
    enable: true
    default_lang: ruby
    span:
      class: 'highlight'
    block:
      class: 'codehilite'
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-MRTV3GCJW1

# Authors
authors:
  Daniel:
    name: Daniel
    display_name: Daniel Vera
    avatar: 'assets/images/mesmall.png'
    description: "Le pupu le mate le gua gua"
# Social
social:
  instagram:  
  
# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives